ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "managerPin" TEXT;
ALTER TABLE "OrderItem" ADD COLUMN IF NOT EXISTS "voidedAt" TIMESTAMP(3);
ALTER TABLE "OrderItem" ADD COLUMN IF NOT EXISTS "voidReason" TEXT;
